[package]
name = "rusty_snake"
version = "0.1.0"
authors = ["cubetastic <cubetastic33@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
rand = "0.6"
crossterm = "0.10"
tui = { version = "0.6.2", default-features = false, features = ["crossterm"] }
